version: "3.3"

services:
  broker:
    image: rabbitmq
    container_name: message-broker
    ports:
      - "5672:5672"
  
  backend:
    image: redis
    container_name: celery-backend
    ports:
      - "6379:6379"

  gcs-celery-worker:
    build: ./gcs-celery-worker-src/
    container_name: gcs-celery-worker
    environment: 
      GOOGLE_APPLICATION_CREDENTIALS: "/home/dibyasom/streamer/assets/creds.json"
    volumes:
      - shared-source-code:/home/dibyasom/streamer/workspace:ro
      - ./gcs-celery-worker-src/secret/:/home/dibyasom/streamer/assets:ro
    links:
      - broker
      - backend
    depends_on:
      - broker
      - backend

  stream-handle:
    build: ./stream-handle-src/
    container_name: stream-handle
    volumes:
      - shared-source-code:/home/dibyasom/shredder/workspace:rw
      - ./stream-handle-src/src:/home/dibyasom/shredder/assets:rw
    depends_on:
      - gcs-celery-worker

volumes: 
  shared-source-code: