version: "3.3"

services:
  broker:
    image: rabbitmq
    container_name: message-broker
    ports:
      - "5672:5672"
  
  backend:
    image: redis
    container_name: celery-backend
    ports:
      - "6379:6379"

  gcs-celery-worker:
    build: ./gcs-celery-worker-src/
    container_name: gcs-celery-worker
    environment: 
      GOOGLE_APPLICATION_CREDENTIALS: "/build/secret/creds.json"
    volumes:
      - shared-source-code:/build/workspace:rw
    links:
      - broker
      - backend

  stream-handle:
    build: ./stream-handle-src/
    container_name: stream-handle
    environment: 
      GOOGLE_APPLICATION_CREDENTIALS: "/build/secret/creds.json"
    volumes:
      - shared-source-code:/build/workspace:rw
      - ./stream-handle-src/src:/build/assets/
    links:
      - broker
      - backend
      - gcs-celery-worker

volumes: 
  shared-source-code: